{
 "title": "Hoegaarden",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Outgoing requests latency (TP95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, path) (rate(ticketbox_hoegaarden_http_outgoing_request_duration_histogram_seconds_bucket[1m])))",
     "legendFormat": "{{method}} - {{path}} - {{code}}"
    }
   ]
  },
  {
   "title": "ShopeePay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(code, path, method) (rate(ticketbox_hoegaarden_http_outgoing_requests_total{recipient=\"shopee_pay_service\"}[1m]))",
     "legendFormat": "{{method}} - {{path}} - {{code}}"
    }
   ]
  },
  {
   "title": "Tiki Payment Portal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(code, method, path) (rate(ticketbox_hoegaarden_http_outgoing_requests_total{recipient=\"tiki_volvo_service\"}[1m]))",
     "legendFormat": "{{method}} - {{path}} - {{code}}"
    }
   ]
  },
  {
   "title": "Inbound HTTP Throughput (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(http_method, http_status_code, http_route) (increase(http_server_total_requests_ratio_total{app=\"hoegaarden\", http_method!=\"OPTIONS\"}[1m]))",
     "legendFormat": "{{http_method}} {{http_route}} - {{http_status_code}}"
    },
    {
     "expr": "sum(increase(http_server_total_requests_ratio_total{app=\"hoegaarden\", http_method!=\"OPTIONS\"}[1m]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Inbound request duration (TP95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_method, http_status_code, http_route) (rate(http_server_duration_milliseconds_bucket{app=\"hoegaarden\"}[10m])))",
     "legendFormat": "{{http_method}} {{http_route}} - {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Inbound HTTP response size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(http_method, http_route, http_status_code) (rate(http_server_response_size_bytes_bucket{app=\"hoegaarden\", http_status_code=\"200\"}[10m]))",
     "legendFormat": "{{http_method}} {{http_route}} - {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (http_server_total_requests_ratio_total{kubernetes_namespace=\"default\", app=\"hoegaarden\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submit order info (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(is_success, error_msg) (increase(submit_order_info_total{app=\"hoegaarden\", kubernetes_namespace=\"default\"}[1m]))",
     "legendFormat": "is_success: {{is_success}} {{error_msg}}"
    }
   ]
  },
  {
   "title": "Submit ticket info (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(is_success, error_msg) (increase(submit_ticket_info_total{app=\"hoegaarden\"}[1m]))",
     "legendFormat": "is_success: {{is_success}} {{error_msg}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{kubernetes_namespace=\"$namespace\", app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{kubernetes_namespace=\"$namespace\", app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{kubernetes_namespace=\"$namespace\", app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{kubernetes_namespace=\"$namespace\", app=\"hoegaarden\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"hoegaarden\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{app=\"hoegaarden\"}"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{kubernetes_namespace=\"$namespace\", app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{app=\"hoegaarden\"} - go_memstats_other_sys_bytes{app=\"hoegaarden\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{app=\"hoegaarden\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{app=\"hoegaarden\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{app=\"hoegaarden\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{app=\"hoegaarden\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app=\"hoegaarden\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{app=\"hoegaarden\"} - go_memstats_frees_total{app=\"hoegaarden\"}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{app=\"hoegaarden\"}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{app=\"hoegaarden\"}[1m])"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app=\"hoegaarden\"}[1m])"
    }
   ]
  }
 ]
}